### ISSUE TITLE
CDATA tags crashes parser

### ISSUE THREAD

**Issue by Raymo111** [kobjects/ktxml#3]
I'm porting DAV4jvm to Java >= 9 using ktxml (it used to use xpp3 which isn't compatible with Java 9's new modules system), and one of the tests there failed because MiniXmlPullParser threw an `IndexOutOfBounds` exception when parsing:
```xml
<test><![CDATA[Test 1</test><test><garbage/>Test 2]]></test>
```
This wasn't something I could fix there, so I tested a simpler CDATA tag:
```
<text><![CDATA[Hello World]]></text>
```
When this also failed I dug into the ktxml code and figured out that `peekType()` was `peek()`ing too far ahead sometimes and causing problems, as well as not handling CDATA attributes.

**Comment by stefanhaustein** [comment]
Thanks for the report & fix!
